### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by khssnv** [TalismanSociety/talisman-connect#16]
Hi guys! Looks like these tools simplify wallets integration a lot! Thank you!

Are there any plans for Vue.js support? We would like to use this in our telescope NFTs dapp https://telescope.merklebot.com/ we in @merklebot are developing with Vue.

**Comment by juliuscarvajal** [comment]
> Hi guys! Looks like these tools simplify wallets integration a lot! Thank you!
> 
> Are there any plans for Vue.js support? We would like to use this in our telescope NFTs dapp https://telescope.merklebot.com/ we in @merklebot are developing with Vue.

We want to support Vue but just don't have the bandwidth at the moment as most of the Dapps use React.
We welcome PRs from everyone and would highly appreciate a Vue submission to this monorepo. Talisman will be issuing Commendations NFTs for such valuable contributions.

https://medium.com/we-are-talisman/the-road-to-community-ownership-32f75bdb76b9

If you do, you can build around this package: https://github.com/TalismanSociety/talisman-connect/tree/master/libs/wallets to create a Vue modal.

This repo is using NX mono repo tooling. I'll need to find time to write a contributing readme.

**Comment by chidg** [comment]
Closing as stale
