### ISSUE TITLE
getWalletBySource() sometimes fails on immediate call after page load 

### ISSUE THREAD

**Issue by rossbulat** [TalismanSociety/talisman-connect#25]
If you call `getWalletBySource(wallet)` as soon as a page loads, extensions can sometimes not be found. This is happening in React if call `getWalletBySource` inside a `useEffect` hook, for example, giving the following `catch` error:

<img width="580" alt="Screenshot 2022-06-06 at 12 05 42" src="https://user-images.githubusercontent.com/13929023/172149329-e8875a5a-8d44-4037-a2a1-909e5e0a5a8f.png">

To overcome this temporarily I have wrapped the parent function in a setTimeout:
```
setTimeout(() => getExtensionsAccounts(), 200); // getWalletBySource is inside this function
```
So it appears there is some missing logic to `await` for some initialisation to happen that enables extensions to become discoverable.

**Comment by chidg** [comment]
Hi @rossbulat , thanks for the report and apologies for the delay in responding. We are currently overhauling this repo and closing off old issues. I expect by this point you have well and truly moved on from this problem, so I'll close this one, but we'll ensure that the next version of the library accounts for this issue.
