### ISSUE TITLE
Ability to connect all accounts in 1 click

### ISSUE THREAD

**Issue by rossbulat** [TalismanSociety/talisman-connect#26]
I currently have to manually click through all the accounts I want to connect to a Dapp.
 It would be nice to have a Select All button to have all accounts selected. 

UI in question:

<img width="358" alt="Screenshot 2022-06-12 at 13 24 17" src="https://user-images.githubusercontent.com/13929023/173233061-065683c0-80fa-4901-a4b7-55b215496a1f.png">

**Comment by chidg** [comment]
Hi @rossbulat,
Thanks for your the feature request. I'll close this, because this repo is actually for `talisman-connect`, which is a utility for dapps to implement connecting to the Talisman wallet, rather than the wallet itself, but I've added the idea to our internal feature tracking process.
