### ISSUE TITLE
Choose account types to inject

### ISSUE THREAD

**Issue by SwamiTLSM** [TalismanSociety/talisman-connect#30]
All the dapp dev to choose if the wallet accepts substrate or evm or both accounts when connecting. This will show the relevant accounts to the user when they choose the account to connect.

**Comment by SwamiTLSM** [comment]
this  functionality also need to be handled in the extension

**Comment by chidg** [comment]
IIRC this was primarily due to some Substrate dapps crashing when EVM type accounts were injected. This problem has been resolved by the ecosystem now and it is no longer necessary to differentiate on our side, since it is a dapp responsibility.
