### ISSUE TITLE
[Support] Kuma Wallet 

### ISSUE THREAD

**Issue by 0xslipk** [TalismanSociety/talisman-connect#44]
Hi guys, 

We want to reach out to talk about adding support for Kuma on [talisman-connect](https://github.com/TalismanSociety/talisman-connect).

Kuma Wallet is the first of its kind, a cross-chain wallet that offers seamless management and transfer of assets between EVM and WASM chains.

## Our vision

- **User-friendly wallet**: The wallet has been developed with an emphasis on simplifying the management of EVM and WASM accounts, making it easy and convenient for users to handle their assets.

- **Seamless asset transfer**: Kuma Wallet enables users to securely transfer their assets between accounts on different chains, eliminating the need for complex and time-consuming processes.

- **Safe platform for interaction with dApps**: The wallet provides a safe and intuitive platform for users to sign messages and interact with dApps, ensuring a seamless user experience.

- **Transparency and accountability**: Kuma Wallet displays transaction details and links to scanner/explorer pages, promoting transparency and accountability in all transactions.

- **Decentralized and open-source nature**: The wallet has been designed with a focus on maintaining its decentralization and open-source nature, ensuring its trustworthiness and security.

- **Comprehensive user experience**: Kuma Wallet aims to cover more than 90% of its main functionalities to provide a comprehensive user experience, making it a one-stop solution for all cross-chain asset management needs.

The [project](https://github.com/blockcoders/kuma-wallet) is currently under development, but we are moving fast and going to ship it very soon.

Let's us know what do you think.

Thanks,

**Comment by chidg** [comment]
Hi @0xslipk , apologies for the delay, we have been lax with maintaining this repo. We are currently tidying up and closing off issues. We'd be happy to include Kuma in future versions of this library, please follow examples like #54 and #52.
