### ISSUE TITLE
Question: Why do you have your own web3Enable?

### ISSUE THREAD

**Issue by niklasp** [TalismanSociety/talisman-connect#45]
In your repo i found, you write your own `web3Enable` which looks quite similar to the one from `@polkadot/extension-dapp`. 

https://github.com/TalismanSociety/talisman-connect/blob/c2e47ae241a2a8e8b09f08da4478d041040e3090/packages/extension-dapp/src/bundle.ts#L74

I am asking because I have a hard time trying to connect polkadotjs to my next app. It works, but it seems, that the `web3Enable` function from polkadot does not work when dynamically imported = the Promise does not return the Injected extension. I have ~ the following code, and thought you could help? Did you face a similar issue or am I on the wrong path?

```js
const { web3Accounts, web3Enable, web3FromAddress, web3AccountsSubscribe } = await import(
    "@polkadot/extension-dapp"
);
const allInjected = await web3Enable('Tokengated Polkadot Demo');
const allAccounts = await web3Accounts();
```
https://github.com/niklasp/polkadot-js-tokengated-webssite/blob/6d72c2cc895612cee03640ca5c2aef3b781de651/context/polkadotExtensionContext.tsx#L35

`allAccounts` is only defined after a user reloads the page but the not for the first time, immediately after I allow the extension access to my dApp

**Comment by chidg** [comment]
Hi @niklasp, it's a little strange to dynamically import a library inside an effect like that. It doesn't surprise me that it isn't working. We provide an example of how to subscribe to accounts and update component state in our readme, you can easily adapt it to use the original `@polkadot/extension-dapp` if you prefer. https://github.com/TalismanSociety/talisman-connect#example

**Comment by chidg** [comment]
Closing, let us know if you need more assistance @niklasp
