### ISSUE TITLE
need a slider on Modal-module_modal-content-body

### ISSUE THREAD

**Issue by arnobase** [TalismanSociety/talisman-connect#47]
when a large number on account is selected, there is no slider to scroll the content 
I don't know how to override the style of the div "Modal-module_modal-content-body__xxxxxxxx"
the only workaround I found was to use 
`#react-portal-modal-container div div {
  overflow: auto;
}`
but this also include the loader when the wallet is being activated the first time

**Comment by chidg** [comment]
Thanks for the comment @arnobase and apologies for the delay in responding. We are currently overhauling this repo and preparing for a new version of the library. We will not fix this issue in the current version but will leave it open for future versions. It would be helpful if you could post a screenshot of the problem so we can ensure we accomodate the use case in the design of the new version. Thanks.

**Comment by arnobase** [comment]
thanks for feedback, I'm glad to know that there will be a new version and will be happy to test it when available
for the current bug, this is easy to reproduce, just connect a quiet large number of account (like 10) on a dApp and you'll see that there is no slider and you can't scroll the list 
<img width="694" alt="Capture d’écran 2023-10-26 à 08 09 34" src="https://github.com/TalismanSociety/talisman-connect/assets/8094810/ce0cf93f-0ae6-4947-ac25-1231ab46f5d3">
