### ISSUE TITLE
Is there a way to filter accounts?

### ISSUE THREAD

**Issue by samelamin** [TalismanSociety/talisman-connect#48]
Hi all

Great work, this repo will save us alot of time 

Quick question. Can I filter accounts from the wallet select? We already know only certain addresses can take an action so we want to only show those accounts even if the user has more accounts associated with their wallet 

I am guessing we can do something using `onWalletSelected` but is there a better way to handle this? 

Essentially, we don't want to give the users options to use an account we know won't work.

**Comment by chidg** [comment]
Hi @samelamin, thanks for the comment, and apologies for the slow response. We are currently resurrecting this library after some time unmaintained. We don't plan on adding more features to this version however we will be considering an updated version with features like account filtering soon.
