### ISSUE TITLE
Test DApp build error

### ISSUE THREAD

**Issue by ERussel** [TalismanSociety/talisman-connect#51]
Hey hey! I am trying to run test dapp which comes with the repo on my Apple Macbook M2 but receive an error. After cloning the repo and going into it I run the following commands:

1) yarn install

2) yarn run build

But the build fails with the following error:

<img width="512" alt="Screenshot 2023-07-14 at 14 52 36" src="https://github.com/TalismanSociety/talisman-connect/assets/570634/c9ee634a-aab8-438c-b802-b61c8f4d23c6">

**Comment by chidg** [comment]
Closed by #54
